const v3Kit=(name,mode,desc,color,asset,opts={})=>({name,mode,desc,color,asset:`assets/fx/v3-${asset}.png`,...opts});
export const CLASSIC_SKILLS={
  ein:v3Kit('棱镜守夜','guard','展开棱镜壁垒，获得 34% 最大生命护盾并嘲讽 2.2 秒；护盾被击破时反射一次 24% 伤害。','#78efff','ward',{shield:.34,taunt:2.2,counter:.24,attackStyle:'blade'}),
  kouichi:v3Kit('霓虹轮刃','dash','滑向最远敌人，造成 215% 攻击伤害并波及相邻目标；每命中一人回复 18% 伤害生命。','#ff7bd4','blade',{target:'far',mult:2.15,splash:.5,lifesteal:.18,attackStyle:'blade'}),
  yua:v3Kit('记忆回收站','single','向最远敌人发射记忆碎片，造成 225% 法术伤害，烧毁 45% 当前法力并沉默 1.8 秒。','#b989ff','void',{target:'far',mult:2.25,manaBurn:.45,silence:1.8,attackStyle:'arc'}),
  goutan:v3Kit('忠犬拦截','guardLink','给生命最低的队友与自身各套上护盾，并建立拦截链接：队友下一次受击由勾檀分担 30%。','#ffb36b','ward',{allyShield:.30,selfShield:.20,taunt:1.8,link:.30,attackStyle:'blade'}),
  yujiu:v3Kit('天线锁定','single','锁定最远敌人，造成 180% 远程伤害并削减 24 点护甲；命中后下一枚普攻自动弹向附近敌人。','#8fe8ff','arc',{target:'far',mult:1.8,shred:24,bounce:true,attackStyle:'shot'}),
  songlv:v3Kit('根系重击','burst','以根锤震击周围敌人，造成 150% 伤害、眩晕 0.8 秒并回复自身 20% 造成伤害的生命。','#9be36a','blade',{mult:1.5,stun:.8,lifesteal:.20,attackStyle:'blade'}),
  likou:v3Kit('急救快闪','heal','治疗生命比例最低的队友 210% 攻击生命，同时附加 10% 最大生命护盾并净化其控制。','#ff9ab6','ward',{heal:2.1,shield:.10,cleanse:true,attackStyle:'arc'}),
  agari:v3Kit('应援心拍','team','全队回复 90% 攻击生命并获得 8% 最大生命护盾；3 秒内首次普攻额外产生一次心拍爆发。','#ff6fae','arc',{heal:.9,shield:.08,tempo:true,attackStyle:'pulse'}),
  hoshimi:v3Kit('月猫跃迁','dash','扑向生命比例最低的敌人，造成 235% 伤害并施加 2 秒流血；击杀后立刻刷新一次位移。','#dca3ff','blade',{target:'low',mult:2.35,bleed:.018,bleedDuration:2,attackStyle:'blade'}),
  chiharu:v3Kit('夜岚折返','cleave','向前方扇区斩出两道夜岚，合计造成 165% 伤害并使命中者受到的下一次普攻伤害提高 25%。','#8fbcff','blade',{mult:.825,hits:2,wound:.25,attackStyle:'blade'}),
  suiji:v3Kit('十小时续航','support','为除自身外的队友回复 28 点法力并治疗 60% 攻击生命；同时获得 18% 攻速，持续 4 秒。','#8ddc9b','ward',{mana:28,heal:.6,haste:.18,attackStyle:'pulse'}),
  kanban:v3Kit('海獭缓冲层','guard','吸收 45% 最大生命伤害，获得 35% 格挡，持续 4 秒；格挡成功时向攻击者喷出水花减速。','#7ed7d9','ward',{shield:.45,block:.35,slow:.20,attackStyle:'blade'}),
  zhouyi:v3Kit('破盾读秒','passive','被动：普通攻击优先拆除护盾；目标无护盾时，下一次攻击造成额外 80% 破防伤害。','#c77dff','void',{passive:true,attackHit:'shieldbreak',attackStyle:'blade'}),
  yuji:v3Kit('雨幕偏航','passive','被动：雨幕庇护——雨纪每 2 次普攻凝结 1 层「雨露」（至多 2 层）；受到攻击时消耗 1 层雨露必定闪避该次攻击，并召唤雨幕：获得 8% 最大生命护盾、下一次普攻附带减速。无雨露时保留 25% 概率格挡（伤害减半）兜底。','#72c9ff','ward',{passive:true,attackHit:'rainveil',attackStyle:'shot'}),
  tiandou:v3Kit('点心补给线','heal','把点心投向两名最需要治疗的队友，各回复 145% 攻击生命并获得 8% 护盾；护盾破裂时回复 8 点法力。','#ffc56d','ward',{heal:1.45,healN:2,shield:.08,mana:8,attackStyle:'arc'}),
  aza:v3Kit('节拍装甲','team','以鼓点强化全队：回复 70% 攻击生命、攻击 +12%，并在施法者脚下留下 2 秒震荡圈。','#ff8b8b','arc',{heal:.7,attack:.12,zone:{r:1,dur:2000,dps:.18},attackStyle:'pulse'}),
  pako:v3Kit('善意溢出','heal','治疗生命最低的队友 230% 攻击生命，溢出治疗转化为 18% 最大生命护盾，并压低其受到的治疗削减。','#73d6e8','ward',{heal:2.3,shield:.18,attackStyle:'arc'}),
  zhijin:v3Kit('紫藤追迹','dash','沿紫藤轨迹突进最远敌人，造成 240% 伤害并窃取 18% 伤害生命；命中后目标 2 秒内无法获得护盾。','#e69bff','blade',{target:'far',mult:2.4,lifesteal:.18,noShield:2,attackStyle:'blade'}),
  sishi:v3Kit('四季转盘','chain','向最多 4 个敌人发射季节弹：春减速、夏烧蓝、秋流血、冬冻结，每跳伤害递减。','#ffd27d','arc',{targets:4,mults:[1.25,1.05,.88,.72],season:true,attackStyle:'shot'}),
  sumi:v3Kit('墨龙入砚','teamShield','为全队附加 18% 最大生命护盾并获得 10% 减伤；墨龙会优先吞掉一次控制效果。','#a58bff','void',{shield:.18,dr:.10,cleanse:true,attackStyle:'arc'}),
  yukie:v3Kit('上勾拳三连','combo','连续三段锁定同一目标：100%／110%／160% 伤害，第三段击飞并附加 1.5 秒流血。','#ff9b7b','blade',{target:'near',hits:3,mults:[1,1.1,1.6],stun:.45,bleed:.015,bleedDuration:1.5,attackStyle:'blade'}),
  miting:v3Kit('看破真相','single','揭开攻击最高敌人的弱点，造成 205% 法术伤害并削减 35% 魔抗；其下一次技能伤害反噬自身。','#ffe49b','arc',{target:'hi',mult:2.05,sunder:.35,reflectSkill:.30,attackStyle:'arc'}),
  xuezhu:v3Kit('冰烛禁区','zone','冻结最远敌人 2 秒并造成 170% 伤害，在脚下生成 2.7 秒冰封禁区。','#9fe8ff','arc',{target:'far',mult:1.7,freeze:2,zone:{r:1,dur:2700,dps:.35},attackStyle:'arc'}),
  zeyin:v3Kit('泽畔回声','team','治疗全队 100% 攻击生命，并让敌方全体受到的治疗降低 25%，持续 4 秒；每个受伤队友回响一次水波。','#79e6d5','ward',{heal:1,enemyHealDown:.25,attackStyle:'pulse'}),
  sanli:v3Kit('梦境三拍','chain','对 3 名敌人进行梦境连锁，造成 160%／120%／90% 法术伤害；最后一跳使目标沉睡 0.6 秒。','#f29eff','arc',{targets:3,mults:[1.6,1.2,.9],stun:.6,attackStyle:'pulse'}),
  diansu:v3Kit('邪修石符','single','在攻击最高敌人身上刻下石符，造成 200% 伤害并石化 2.2 秒；若目标有护盾则额外碎盾。','#d9c8a6','void',{target:'hi',mult:2,petrify:2.2,shieldbreak:true,attackStyle:'arc'}),
  lianshiye:v3Kit('失忆挽歌','single','对最近敌人造成 180% 伤害、沉默 3 秒并烧毁 40% 当前法力；目标每次施法都会再受一次回响伤害。','#c99dff','void',{mult:1.8,silence:3,manaBurn:.4,echo:.35,attackStyle:'blade'}),
  huize:v3Kit('果冻封印','single','用果冻领域束缚最近敌人，造成 160% 伤害、减速 40% 并附加 3 秒毒伤，同时禁止其获得治疗。','#ff83cf','ward',{mult:1.6,slow:.4,bleed:.015,enemyHealDown:.35,healBlock:3.2,attackStyle:'arc'}),
  shengge:v3Kit('净音祷歌','team','治疗全队 95% 攻击生命并净化控制；净化成功的队友获得 15% 攻速，持续 3 秒。','#fff2a6','ward',{heal:.95,cleanse:true,haste:.15,hasteDuration:3,attackStyle:'pulse'}),
  shadow:v3Kit('熊跃终点','dash','跳向生命最低的敌人，造成 280% 伤害；目标生命低于 40% 时追加 45% 斩杀伤害。','#ffad66','blade',{target:'low',mult:2.8,execute:.45,attackStyle:'blade'}),
  nox:v3Kit('夜莺回响','dash','突进最远敌人造成 240% 伤害，留下一个 2 秒后爆裂的残影；残影爆炸会沉默周围敌人。','#ad8dff','void',{target:'far',mult:2.4,afterimage:true,attackStyle:'blade'}),
  miyue:v3Kit('月影留痕','dashCleave','切入目标后回旋斩击周围敌人，造成 185% 伤害并施加 2 秒流血；每命中一人获得 5% 吸血。','#c39bff','blade',{target:'near',mult:1.85,bleed:.02,bleedDuration:2,lifesteal:.05,attackStyle:'blade'}),
  huali:v3Kit('花礼绽放','heal','治疗两名队友各 160% 攻击生命并回复 18 点法力；受疗者生命越低，治疗越高。','#ffb7d0','ward',{heal:1.6,healN:2,mana:18,attackStyle:'arc'}),
  youyu:v3Kit('幽魂相位','dash','化为幽魂穿过敌阵，对最近敌人造成 220% 纯粹伤害并获得 1.5 秒相位闪避。','#78d9ff','void',{target:'near',mult:2.2,dtype:'pure',phase:1.5,attackStyle:'blade'}),
  quanrong:v3Kit('小狗反甲','guard','获得 50% 最大生命护盾并嘲讽 2.5 秒；护盾期间每次受击反弹 8% 最大生命。','#d7a76b','ward',{shield:.50,taunt:2.5,thorns:.08,attackStyle:'blade'}),
  ruiya:v3Kit('时空封存','zone','冻结最远敌人 2.4 秒并造成 200% 伤害；生成时空区，区域内敌人攻速降低 60%。','#a8b9ff','void',{target:'far',mult:2,freeze:2.4,slow:.6,zone:{r:1,dur:3000,dps:.22},attackStyle:'arc'}),
  mumu:v3Kit('东风润物','team','全队回复 105% 攻击生命并获得 20% 攻速，持续 4 秒；生命满的队友改为获得 10% 护盾。','#9cffb4','ward',{heal:1.05,haste:.20,shield:.10,attackStyle:'pulse'}),
  kroya:v3Kit('混沌裂界','chaos','对攻击最高敌人造成 260% 法术伤害并裂变一次：随机附加冻结、沉默或烧蓝。','#ff8dce','void',{target:'hi',mult:2.6,chaos:true,attackStyle:'arc'}),
  shiliu:v3Kit('浣熊洗劫','single','偷走最近敌人的全部护盾并造成 215% 伤害；若偷到护盾，额外眩晕 0.6 秒。','#f5b46b','blade',{mult:2.15,stealShield:true,stun:.6,attackStyle:'blade'}),
  seki:v3Kit('星蚀低语','field','在自身周围展开星蚀领域，对范围内敌人造成 150% 伤害、沉默 2.6 秒并持续烧蓝。','#7e75ff','void',{mult:1.5,silence:2.6,manaBurn:.35,attackStyle:'pulse'}),
  haruka:v3Kit('白刃拍击','cleave','以白刃拍击周围敌人，造成 180% 伤害并削减 25% 攻击；被削弱者攻击会给白神遥回 4 点法力。','#f6f3ff','blade',{mult:1.8,weaken:.25,mana:4,attackStyle:'blade'}),
  mahiru:v3Kit('绯红旋风','cleave','旋转三圈，每圈对周围敌人造成 90% 伤害并回复 25% 伤害生命；第三圈附加流血。','#ff6b75','blade',{mult:.9,hits:3,lifesteal:.25,bleed:.02,attackStyle:'blade'}),
  nana7mi:v3Kit('鲨皇潮','burst','召唤鲨潮冲撞前方，造成 210% 伤害、拉近敌人并减速 35%；血量越低伤害越高。','#67d4e8','arc',{mult:2.1,slow:.35,pull:true,lowHPBoost:.6,attackStyle:'blade'}),
  liAn:v3Kit('晨露凝霜','field','将全场最危险的敌人群体冻结 1.4 秒并造成 125% 伤害；冻结结束后目标获得易伤。','#e6fbff','arc',{mult:1.25,freeze:1.4,brittle:.22,attackStyle:'arc'}),
  youyi:v3Kit('一心同体','passive','被动：每次普通攻击为自身与生命最低的队友各回复 3% 最大生命；任意一方濒死时共享 20% 护盾。','#ff9f9f','ward',{passive:true,attackHit:'soulmate',attackStyle:'blade'}),
  azi:v3Kit('高音震魂','field','释放高音震魂波，范围内敌人受到 130% 伤害并眩晕 1.5 秒；每命中一人，阿梓获得 6 点法力。','#ffbd6a','arc',{mult:1.3,stun:1.5,mana:6,attackStyle:'pulse'}),
  taodai:v3Kit('桃香结界','teamShield','全队获得 22% 最大生命护盾；桃香结界持续 4 秒，期间全队减伤 20%，桃代嘲讽 2.7 秒。','#ffb1c9','ward',{shield:.22,dr:.20,taunt:2.7,attackStyle:'blade'}),
  miki:v3Kit('星海庇护','heal','治疗 3 名队友各 150% 攻击生命，附加 12% 护盾并回复 12 点法力；优先濒危单位。','#8fd9ff','ward',{heal:1.5,healN:3,shield:.12,mana:12,attackStyle:'arc'}),
  rei:v3Kit('灵界之门','field','开启灵界之门，范围敌人受到 135% 伤害并沉默 2.4 秒；门会把其中一次治疗的 40% 转成伤害。','#b78cff','void',{mult:1.35,silence:2.4,enemyHealDown:.40,attackStyle:'pulse'}),
  rinco:v3Kit('十二点拉闸','cleave','拉下总闸，对周围敌人造成 210% 伤害并沉默 1.8 秒；自身获得 25% 吸血，直到战斗结束。','#ff5f70','void',{mult:2.1,silence:1.8,lifesteal:.25,attackStyle:'blade'})
};

const hash=(id,seed)=>{let h=seed;for(const ch of id)h=(h*31+ch.charCodeAt(0))>>>0;return h;};
export function classicAttackProfile(id){const k=CLASSIC_SKILLS[id]||{},h=hash(id,41);return {style:k.attackStyle||['blade','shot','arc','pulse','burst'][h%5],color:k.color,asset:k.asset,mult:.93+(h%9)*.025,proc:.14+(hash(id,73)%5)*.035,potency:.008+(hash(id,89)%7)*.002,onHit:k.attackHit||['none','bleed','slow','spark','mana'][hash(id,73)%5],glyph:({blade:'╱',shot:'➤',arc:'◇',pulse:'✦',burst:'✹'}[k.attackStyle]||'✦')};}

export const CLASSIC_MARKS={
  ein:{label:'折光盾',amp:.10,dur:3.6,kind:'ward'}, kouichi:{label:'轮刃',amp:.12,dur:3.0,kind:'skate'}, yua:{label:'失忆',amp:.13,dur:3.4,kind:'prism'}, goutan:{label:'忠犬',amp:.09,dur:4.0,kind:'ward'}, yujiu:{label:'锁定',amp:.10,dur:3.2,kind:'prism'}, songlv:{label:'根锤',amp:.12,dur:3.3,kind:'ward'}, likou:{label:'急救',amp:.08,dur:3.8,kind:'lotus'}, agari:{label:'应援',amp:.08,dur:3.0,kind:'lotus'}, hoshimi:{label:'猫爪',amp:.14,dur:2.8,kind:'skate'}, chiharu:{label:'夜岚',amp:.12,dur:3.0,kind:'skate'},
  suiji:{label:'续航',amp:.07,dur:4.4,kind:'lotus'}, kanban:{label:'海壳',amp:.09,dur:4.4,kind:'ink'}, zhouyi:{label:'破盾',amp:.12,dur:3.2,kind:'prism'}, yuji:{label:'雨幕',amp:.08,dur:4.0,kind:'lotus'}, tiandou:{label:'点心',amp:.09,dur:3.6,kind:'lotus'}, aza:{label:'节拍',amp:.10,dur:3.2,kind:'prism'}, pako:{label:'善意',amp:.08,dur:4.0,kind:'lotus'}, zhijin:{label:'紫藤',amp:.13,dur:2.9,kind:'skate'}, sishi:{label:'四季',amp:.15,dur:3.0,kind:'prism'}, sumi:{label:'墨龙',amp:.11,dur:4.2,kind:'ink'},
  yukie:{label:'连段',amp:.13,dur:2.8,kind:'skate'}, miting:{label:'看破',amp:.14,dur:3.1,kind:'prism'}, xuezhu:{label:'冰烛',amp:.14,dur:3.3,kind:'prism'}, zeyin:{label:'泽歌',amp:.10,dur:3.8,kind:'lotus'}, sanli:{label:'三重奏',amp:.13,dur:3.0,kind:'prism'}, diansu:{label:'石符',amp:.15,dur:3.4,kind:'ink'}, lianshiye:{label:'挽歌',amp:.12,dur:3.2,kind:'prism'}, huize:{label:'果冻',amp:.11,dur:3.5,kind:'lotus'}, shengge:{label:'净音',amp:.09,dur:3.8,kind:'lotus'}, shadow:{label:'熊跃',amp:.16,dur:2.7,kind:'skate'}, nox:{label:'夜莺',amp:.15,dur:2.8,kind:'skate'},
  miyue:{label:'月影',amp:.14,dur:3.0,kind:'skate'}, huali:{label:'花礼',amp:.09,dur:4.0,kind:'lotus'}, youyu:{label:'幽魂',amp:.16,dur:3.4,kind:'ink'}, quanrong:{label:'小狗',amp:.10,dur:4.5,kind:'ink'}, ruiya:{label:'时空',amp:.15,dur:3.3,kind:'prism'}, mumu:{label:'东风',amp:.10,dur:4.0,kind:'lotus'}, kroya:{label:'裂界',amp:.16,dur:3.0,kind:'prism'}, shiliu:{label:'洗劫',amp:.14,dur:3.1,kind:'skate'}, seki:{label:'星蚀',amp:.15,dur:3.2,kind:'prism'}, haruka:{label:'白刃',amp:.14,dur:3.0,kind:'skate'}, mahiru:{label:'绯旋',amp:.16,dur:2.9,kind:'skate'},
  nana7mi:{label:'鲨皇',amp:.17,dur:3.0,kind:'ink'}, liAn:{label:'晨霜',amp:.16,dur:3.6,kind:'prism'}, youyi:{label:'同体',amp:.12,dur:4.0,kind:'ink'}, azi:{label:'高音',amp:.16,dur:3.2,kind:'prism'}, taodai:{label:'桃香',amp:.12,dur:4.2,kind:'ink'}, miki:{label:'星海',amp:.12,dur:4.0,kind:'lotus'}, rei:{label:'灵门',amp:.17,dur:3.3,kind:'prism'}, rinco:{label:'拉闸',amp:.18,dur:2.8,kind:'ink'}
};
